<?php

/**
 * @file
 * Primary module hooks for storm_cms_layout_builder module.
 */

use Drupal\Component\Serialization\Json;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function storm_cms_layout_builder_form_node_layout_builder_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#attributes']['class'][] = 'storm-cms-layout-builder-form';
  $form['#attached']['library'][] = 'storm_cms_layout_builder/form';
  unset($form['revision_information']);
  $form['actions']['#weight'] = 200;
  $form['actions']['#attributes']['class'][] = 'storm-cms-layout-builder-form-actions';
  $form['revision']['#access'] = FALSE;
  $form['moderation_state']['#access'] = FALSE;
}

/**
 * Implements hook_link_alter().
 */
function storm_cms_layout_builder_link_alter(&$variables) {
  /** @var Drupal\Core\Url $url */
  $url = $variables['url'];
  $config = \Drupal::config('layout_builder_modal.settings');

  if (!$url->isRouted()) {
    return;
  }

  $routes = [
    'section_library.add_template_to_library',
    'section_library.add_section_to_library'
  ];

  if (in_array($url->getRouteName(), $routes) && isset($config)) {
    $data_dialog_options = Json::encode([
      'width' => $config->get('modal_width'),
      'height' => $config->get('modal_height'),
      'target' => 'layout-builder-modal',
      'autoResize' => $config->get('modal_autoresize'),
      'modal' => TRUE,
    ]);

    $variables['options']['attributes']['data-dialog-options'] = $data_dialog_options;
    $variables['options']['attributes']['data-dialog-type'] = 'dialog';
    unset($variables['options']['attributes']['data-dialog-renderer']);
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function storm_cms_layout_builder_preprocess_page(&$variables) {
  $route = \Drupal::routeMatch()->getRouteName();
  if($route === 'layout_builder.overrides.node.view') {
    $variables['#attached']['library'][] =  'storm_cms_layout_builder/layout-builder';
  }
}
